### ISSUE TITLE
Change Header format from JSON to YAML.

### ISSUE THREAD

**Issue by anarcher** [anarcher/linen#1]
Currently I considered below this.

```
{
   "post" : true
   "title" : "Article"
}

---

# Article 1

...
```

Basically, `JSON` is not good option for some kind of simple configuration. 
For example commenting is not easy in JSON.
So Then, Header format changes from JSON to YAML.

ps) This is from an advice from @outsideris. Thanks.

**Comment by outsideris** [comment]
:+1:
